services:
  web-greet:
    build: .
    container_name: greet
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"

